#
# Chart: neops preview environment
#

image:
  tag: develop

imagePullSecrets:
  - name: zebbra-kube-pull-secret

app:
  replicaCount: 2

worker:
  replicaCount: 2

openvpn:
  enabled: true
  configName: openvpn-config

# flower:
#   enabled: true

secrets:
  DJANGO_SECRET_KEY: e068c0c112632ed803ab19011b45d7c3
  DATABASE_URL: postgres://neops:delaware-crank-acrimony@postgres.kubedb/neops_preview
  REDIS_URL: redis://neops-preview-redis-master:6379/0
  ELASTICSEARCH_HOSTS: http://neops-preview-es-master:9200

config:
  NEOPS_PLUGINS: "neops_cron neops_auth_django neops_permissions_simple"
  DJANGO_ALLOWED_HOSTS: "*"
  DEBUG: "False"
  ELASTICSEARCH_DSL_INDEX_SHARDS: "3"
  ELASTICSEARCH_DSL_INDEX_REPLICAS: "1"
  ELASTICSEARCH_DSL_INDEX_FIELDS_LIMIT: "10000"
  SENTRY_ENVIRONMENT: preview

ingress:
  enabled: true
  annotations:
    kubernetes.io/tls-acme: "true"
  hosts:
    - preview.neops.io
  tls:
    - secretName: neops-preview-tls
      hosts:
        - preview.neops.io

elasticsearch:
  deployChart: true

  clusterName: neops-preview-es

  volumeClaimTemplate:
    storageClassName: "rook-ceph-block"
    accessModes: ["ReadWriteOnce"]
    resources:
      requests:
        storage: 5Gi

kibana:
  deployChart: true

  elasticsearchHosts: http://neops-preview-es-master:9200

  ingress:
    enabled: true
    annotations:
      kubernetes.io/tls-acme: "true"
    path: /
    hosts:
      - kibana.preview.neops.io
    tls:
      - secretName: kibana-tls
        hosts:
          - kibana.preview.neops.io

redis:
  deployChart: true

  usePassword: false

  master:
    persistence:
      enabled: true
      storageClass: rook-ceph-block
      size: 5Gi


etcd:
  deployChart: true  
  persistence:
    enabled: false