#
# Chart: neops preview environment
#

image:
  tag: develop

imagePullSecrets:
  - name: zebbra-kube-pull-secret

existingSecret: "neops-preview"

app:
  replicaCount: 2
  service:
    port: 8000

worker:
  replicaCount: 2

# there is currently not yet a openvpn-config map in our k8s
# openvpn:
#   enabled: true
#   configName: openvpn-config

secrets:
  DJANGO_SECRET_KEY: e068c0c112632ed803ab19011b45d7c3
  DATABASE_URL: postgres://neopspreview:the-password-from-secret@neops-postgres.neops:5432/neopspreview
  REDIS_URL: redis://neops-preview-redis-master:6379/0
  ELASTICSEARCH_HOSTS: http://neops-preview-es-master:9200

config:
  NEOPS_PLUGINS: "neops_cron neops_auth_django neops_permissions_simple"
  DJANGO_ALLOWED_HOSTS: "*"
  DEBUG: "False"
  ELASTICSEARCH_DSL_INDEX_SHARDS: 3
  ELASTICSEARCH_DSL_INDEX_REPLICAS: 2
  ELASTICSEARCH_DSL_INDEX_FIELDS_LIMIT: 10000
  ELASTICSEARCH_DSL_AUTOSYNC: true
  ELASTICSEARCH_DSL_FLUSH_CACHE_SIZE: 400
  SENTRY_ENVIRONMENT: preview

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 200m
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: preview.neops.io
      paths:
        - path: /
          pathType: Prefix

  tls:
    - secretName: neops-preview-tls
      hosts:
        - preview.neops.io

hooks:
  # disable hooks for faster deployments
  enabled: true

elasticsearch:
  enabled: true

  clusterName: neops-preview-es

  replicas: 3
  minimumMasterNodes: 2
  maxUnavailable: 1

  antiAffinityTopologyKey: "kubernetes.io/hostname"
  antiAffinity: "soft"

  volumeClaimTemplate:
    accessModes: ["ReadWriteOnce"]
    resources:
      requests:
        storage: 5Gi

kibana:
  enabled: true

  replicas: 2

  elasticsearchHosts: http://neops-preview-es-master:9200

  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: 200m
    hosts:
      - host: kibana.preview.neops.io
        paths:
          - path: /
    tls:
      - secretName: neops-preview-kibana-tls
        hosts:
          - preview.neops.io

  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - topologyKey: kubernetes.io/hostname
          labelSelector:
            matchExpressions:
              - key: release
                operator: In
                values: [neops]
              - key: app
                operator: In
                values: [kibana]

redis:
  enabled: true
  usePassword: false

  auth:
    enabled: false

  master:
    persistence:
      enabled: true
      size: 5Gi

  replica:
    persistence:
      enabled: true
      size: 5Gi

  serviceMonitor:
    enabled: true
    interval: 15s
    namespace: neops

etcd:
  enabled: false
  # replicaCount: 3

  # auth:
  #   rbac:
  #     enabled: false

  # persistence:
  #   enabled: true
  #   size: 1Gi

  # pdb:
  #   create: true
  #   minAvailable: 2
  #   # maxUnavailable: 1

  metrics:
    enabled: true
    podMonitor:
      enabled: true
      interval: 15s
      namespace: neops
