#
# Chart: neops-web-client demo environment
#

image:
  tag: latest

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: web-client.demo.neops.io
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: neops-web-client-demo-tls
      host:
        - web-client.demo.neops.io
        - www.web-client.demo.neops.io

backend:
  backendUrl: "https://demo.neops.io/graphql"