apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "neops.fullname" . }}
  labels:
    {{- include "neops.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.config }}
   {{ $key }}: {{ $value | quote }}
{{- end }}
