{{- if and .Values.registry.username .Values.registry.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-quay-registry
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: {{ dict "auths" (dict "quay.io" (dict "username" .Values.registry.username "password" .Values.registry.password "auth" (printf "%s:%s" .Values.registry.username .Values.registry.password | b64enc))) | toJson | quote }}
{{- end }}
