{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "neops.fullname" . }}
  labels:
{{ include "neops.labels" . | indent 4 }}
data:
{{ range $key, $value := .Values.secrets }}
   {{ $key }}: {{ $value | b64enc | quote }}
{{ end }}
{{- end }}
