{{- $secret := lookup "v1" "Secret" .Release.Namespace (include "neops.fullname" .) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "neops.fullname" . }}
  labels:
{{ include "neops.labels" . | indent 4 }}
data:
{{- if $secret -}}
{{ range $key, $value := $secret.data }}
  {{ $key }}: {{ $value | quote }}
{{- end -}}
{{- else -}}
{{ range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end -}}
{{- end -}}
