apiVersion: v1
kind: Service
metadata:
  name: {{ include "neops.fullname" . }}
  labels:
    {{- include "neops.labels" . | nindent 4 }}
spec:
  type: {{ .Values.app.service.type }}
  ports:
    # app
    - port: {{ .Values.app.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "neops.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: app
